---
title: "First Progress Final"
author: "Ege"
date: "12/27/2021"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyverse)
library(magrittr)
library(corrplot)
library(car)
library(readxl) # read excel
library(pander) # table
library(modelr) # add_prediction()
```

```{r}
library(tseries)
library(forecast)
library(fable)
library(readxl)
library(base)
library(writexl)
```

```{r}
data <- read_xlsx("data/SalesData.xlsx")
```

```{r}
for (i in (10))
{

  print(paste(("The models group:"), data[1,i+1]))
  print(paste(("The models screen:"), data[2,i+1]))
  print(paste(("The models country:"), data[3,i+1]))
  print(paste(("The models brand:"), data[4,i+1]))
  print(paste(("Train data:"), data[6:29,i+1]))
  
  sales <- data[6:29,i+1]
  colnames(sales)<-c("a")
  sales<-sales %>%mutate(a=as.numeric(a))
  train <- ts(sales$a,start=c(2019,05), end=c(2021,4), frequency=12)
  print(train)
  
  #TEST DATA
  test<- data[30:35,i+1]
  colnames(test)<-c("b")
  test<-test %>%mutate(b=as.numeric(b))
  test <- ts(test$b,start=c(2021,05), end= c(2021,10),frequency=12)
  print(test)
  
  
  #EXPONENTİAL SMOOTHİNG
  expsmooth <- ets(train)
  forecastexpsmooth <- forecast(expsmooth, h=24)
  plotexp <- autoplot(forecastexpsmooth)
  
  
  #ARIMA
  arima1 <-auto.arima(train)
  arima_forecast<- forecast(arima1)
  arima_plot <- autoplot(arima_forecast)
  arima_plot
  
   #HOLT WINTERS
   #Holt_Winters1 <- HoltWinters(train, alpha = NULL, beta = NULL, gamma = NULL,
             #seasonal = c("additive", "multiplicative"),
             #start.periods = 2, l.start = NULL, b.start = NULL,
             #s.start = NULL,
             #optim.start = c(alpha = 0.3, beta = 0.1, gamma = 0.1),
             #optim.control = list())
   #Holt_Wintersforecast <- forecast(Holt_Winters1)
   #Holt_Winters_plot <- autoplot(Holt_Wintersforecast)

  #HOLT
   Holt <- holt(train, type = c("additive", "multiplicative"), alpha = NULL,
   beta = NULL, lead = NULL, damped = FALSE, phi = NULL, plot = TRUE)
   Holtforecast <- forecast(Holt)
   Holt_plot <- autoplot(Holtforecast)
   Holt_plot
   
   
  #EXPONENTİAL SMOOTHİNG MSE
  expsmoth_mse <- (forecastexpsmooth$mean[1:5]-test[1:5])^2
  exp_sum<- sum(expsmoth_mse)

 #ARIMA MSE
  arima_mse <-(arima_forecast$mean[1:5]-test[1:5])^2
  arima_mse_sum <- sum(arima_mse)

  #HOLT-WINTERS MSE
  #Holt_Winters_mse <- (Holt_Wintersforecast$mean[1:5]-test[1:5])^2
  #Holt_Winters_mse_sum <- sum(Holt_Winters_mse)

  #HOLT MSE
  Holt_mse <- (Holtforecast$mean[1:5]- test[1:5])^2
  Holt_mse_sum <- sum(Holt_mse)

  minimum <- min(sum(Holt_mse), sum(arima_mse), sum(expsmoth_mse))

  if (exp_sum == minimum ){result <- forecastexpsmooth}
  if(arima_mse_sum == minimum){result <- arima_forecast}
  if(Holt_mse_sum == minimum) {result <- Holtforecast}

  autoplot(result)
  head(result)
  print(result)
  
  library(openxlsx)
  wb <- loadWorkbook("data/actualoutput.xlsx")
  addWorksheet(wb,"nx-55-beko-turkey")
  df <- data.frame(result)
  writeData(wb,"nx-55-beko-turkey",df)
  saveWorkbook(wb,"data/actualoutput.xlsx",overwrite = TRUE)
  
  # write_xlsx(x = df,path = "out/actualoutput.xlsx")

  ####SİMULATION####
  
  data2 <- simulate(result$model, nsim=100, seed= NULL)
  
   #EXPONENTİAL SMOOTHİNG
  expsmooth2 <- ets(data2)
  forecastexpsmooth2 <- forecast(expsmooth2, h=24)
  plotexp2 <- autoplot(forecastexpsmooth2)

  #ARIMA
  arima2 <-auto.arima(data2)
  arima_forecast2<- forecast(arima2)
  arima_plot2 <- autoplot(arima_forecast2)

  #HOLT WINTERS
   #Holt_Winters2 <- HoltWinters(data2, alpha = NULL, beta = NULL, gamma = NULL,
             #seasonal = c("additive", "multiplicative"),
             #start.periods = 2, l.start = NULL, b.start = NULL,
             #s.start = NULL,
             #optim.start = c(alpha = 0.3, beta = 0.1, gamma = 0.1),
             #optim.control = list())
   #Holt_Wintersforecast2 <- forecast(Holt_Winters2)
   #Holt_Winters_plot2 <- autoplot(Holt_Wintersforecast2)

  #HOLT
  Holt2 <- holt(data2, type = c("additive", "multiplicative"), alpha = NULL,
  beta = NULL, lead = NULL, damped = FALSE, phi = NULL, plot = TRUE)
  Holtforecast2 <- forecast(Holt2)
  Holt_plot2 <- autoplot(Holtforecast2)

  #EXPONENTİAL SMOOTHİNG MSE
  expsmoth_mse2 <- (forecastexpsmooth2$mean[1:5]-test[1:5])^2
  exp_sum2<- sum(expsmoth_mse2)

 #ARIMA MSE
  arima_mse2 <-(arima_forecast2$mean[1:5]-test[1:5])^2
  arima_mse_sum2 <- sum(arima_mse2)

  #HOLT-WINTERS MSE
   #Holt_Winters_mse2 <- (Holt_Wintersforecast2$mean[1:5]-test[1:5])^2
   #Holt_Winters_mse_sum2 <- sum(Holt_Winters_mse2)

  #HOLT MSE
  Holt_mse2 <- (Holtforecast2$mean[1:5]- test[1:5])^2
  Holt_mse_sum2 <- sum(Holt_mse2)

  minimum2 <- min(sum(Holt_mse2), sum(arima_mse2), sum(expsmoth_mse2))

  if (exp_sum2 == minimum2 ){result2 <- forecastexpsmooth2}
  if(arima_mse_sum == minimum2){result2 <- arima_forecast2}
  if(Holt_mse_sum2 == minimum2) {result2 <- Holtforecast2}

  
  autoplot(result2)
  head(result2)
  print(result2)
  
  
  result$model
  result2$model
  
  library(openxlsx)
  wb <- loadWorkbook("data/simulatedoutput.xlsx")
  addWorksheet(wb,"nx-55-beko-turkey")
  df <- data.frame(result2)
  writeData(wb,"nx-55-beko-turkey",df)
  saveWorkbook(wb,"data/simulatedoutput.xlsx",overwrite = TRUE)
  
  # write_xlsx(x = df,path = "out/simulatedoutput.xlsx")
}
```
